Selected Locations Use Case
teddyyang8/TravelAdvisors pull request #61
Opened 2024-12-01 07:06 UTC by seanwoo12

added implementation of selected locations use case, fixed some bugs

2024-12-01 07:19 UTC, teddyyang8 requested changes

2024-12-01 07:19 UTC, teddyyang8 commented on src/main/java/app/MainWithDB.java
why is suggestedlocationviewmodel passed into selectedlocationview?

2024-12-01 07:19 UTC, teddyyang8 commented on src/main/java/use_case/selected_locations/SelectedLocationsInteractor.java
line 32 return?

2024-12-01 07:19 UTC, teddyyang8 commented on src/main/java/use_case/selected_locations/SelectedLocationsInteractor.java
the map isnt being used? shouldnt it be final SelectedLocationsOutputData selectedLocationsOutputData =
                new SelectedLocationsOutputData(Map);?

2024-12-01 07:21 UTC, teddyyang8 requested changes

2024-12-01 07:21 UTC, teddyyang8 commented on src/main/java/view/SelectedLocationView.java
since the viewmodel is not being used here

2024-12-02 04:02 UTC, teddyyang8 approved these changes

2024-12-02 04:03 UTC, shirleyyzhang approved these changes

2024-12-02 04:03 UTC, merged